### ISSUE TITLE
IDEA - add increase/decrease direction

### ISSUE THREAD

**Issue by saniho** [SNoof85/lovelace-tempometer-gauge-card#12]
Hello, 
as a user, I want to be able to activate a direction icon, to see, if the value incease/decrease

**Comment by SNoof85** [comment]
Hi,

Could be an idea, don't know where to place the direction icon...any idea ?

**Comment by saniho** [comment]
like this for example : 
![image](https://user-images.githubusercontent.com/52693545/103034721-d4d9f780-4565-11eb-961d-ad7fb5f26788.png)

**Comment by SNoof85** [comment]
Will have a look into it

**Comment by saniho** [comment]
I have made my own version, not sure it's the perfect implementation, but I idea : 
1/ add an attribute in the sensor : 
entity_previous: sensor.pressure_previous_xxx
2/ create dynamic sensor : entity_previous: sensor.pressure_previous_xxx with a request : 
get the previous value with 7 digits diffences

    - name: pressure previous xxx
      query: >
              SELECT CAST(state AS FLOAT) as state
              FROM states 
              WHERE entity_id = 'sensor.xxx_pressure' 
              AND last_updated > date('now','-2 day')
              and (cast(state as decimal) > ( select cast(state as decimal) + 7 FROM states 
                 WHERE entity_id = 'sensor.xxx_pressure' 
                 order by state_id desc limit 1 )
              or
                 cast(state as decimal) < ( select cast(state as decimal) - 7 FROM states 
                 WHERE entity_id = 'sensor.xxx_pressure' 
                 order by state_id desc limit 1 ))
              ORDER BY last_updated desc
              limit 1

3/ add in the js this :  two direction up/down, depending of the evolution..or not.

**Comment by SNoof85** [comment]
For trends you can also use : https://www.home-assistant.io/integrations/trend/

**Comment by SNoof85** [comment]
Go away stale
