### ISSUE TITLE
Humidity severity color

### ISSUE THREAD

**Issue by enryf89** [SNoof85/lovelace-tempometer-gauge-card#14]
Hello,
I'd like to set the humidity severity colors in reverse order. That is to say with the lowest value being the most critical.
To be clear, like this:
- Below 20% -> red
- Below 40% -> yellow
- Below 75% -> green
- Above 75% -> light blue

From what I understand form my tests, this in not possible. The colors work only growing from blue to red.
Could you add the feature (or just help me)?

Thanks again, 
Enrico

**Comment by SNoof85** [comment]
Hey,

Sorry but the card is based on actual gauge card in HA. You have the same set of features. I won't have the time to work on a such behaviour.

**Comment by enryf89** [comment]
thanks for the answer. Your suggestion is not exactly what I was trying.
I would have liked the blue to represent "wet" and red "hot". But it's not critical.

thanks again for the card!

**Comment by SNoof85** [comment]
yes, I know what you meant and trying to do. This is not possible at this time. Will have a look if i can find a solution.

**Comment by SNoof85** [comment]
Hey, could you try : https://github.com/SNoof85/lovelace-tempometer-gauge-card/blob/test-for-max/tempometer-gauge-card.js

This has an extra option in severity object called "max".

You can try to setup : 
```
severity:
  green: 40
  yellow: 20
  red: 0
  max: 75
```

**Comment by enryf89** [comment]
nope, I'm sorry, I tried after replacing the _tempometer-gauge.card.js_ and rebooting HA, but it's still green.
<img width="990" alt="image" src="https://user-images.githubusercontent.com/9007104/102931431-ae04be00-449e-11eb-8976-d54d0b5d0642.png">

**Comment by SNoof85** [comment]
Ok. I will set some logging and let you know when a new test will be available !

**Comment by SNoof85** [comment]
OK, then please try again, same branch. I've added a version logging to console. Please ensure that you have v0.7b.
This will ensure you don't have browser cache issue :)

**Comment by enryf89** [comment]
now it works great!
I updated the file and cleaned the browser cache. Now it works like a charm!
I feel like I might have messed up something on the last version upload though...

**Merci beacoup!**

![image](https://user-images.githubusercontent.com/9007104/103094055-917e9800-45fc-11eb-8d5f-c4a23bb3b633.png)

**Comment by SNoof85** [comment]
Reopening - will close with incoming PR :)

Glad it worked ! will include this !
