### ISSUE TITLE
New style "Hygrometer"

### ISSUE THREAD

**Issue by elrhandouri** [SNoof85/lovelace-tempometer-gauge-card#2]
Thanks for this beautiful custome card,
I think it just needs a third style "hygrometer" to be able to use it for humidity as well 👍

**Comment by SNoof85** [comment]
Hey,

Would be nice sure, but i was thinking on wich icons to use for this... If you have any idea :)

**Comment by elrhandouri** [comment]
Hello,
What about those:
mdi-water-off
mdi-water-percent
mdi-water

And maybe the possibility to override them or have a custom type, so we can display any kind of info, 

Thx ;)

**Comment by SNoof85** [comment]
I will have a look first with adding those, then check on how to support materialdesign icons.
