### ISSUE TITLE
different graphics

### ISSUE THREAD

**Issue by wifi75** [SNoof85/lovelace-tempometer-gauge-card#21]
hello why it is diifferent graphics?

![image](https://user-images.githubusercontent.com/31816231/107145981-892cb300-6945-11eb-8b97-def4db26160e.png)

**Comment by SNoof85** [comment]
Hi,
This is a theme issue, nothing related with card, i'm sorry.
You have some theming option on var --card-background-color to make it transparent i guess.

**Comment by SNoof85** [comment]
Woopsie !
Did not wanted to close it :)
Please check my comment above 👍

**Comment by SNoof85** [comment]
Please open the issue back if my comment doesn't solve.
