### ISSUE TITLE
Ability to pass a statistics entity for min/max

### ISSUE THREAD

**Issue by bpetrikovics** [SNoof85/lovelace-tempometer-gauge-card#23]
**Is your feature request related to a problem? Please describe.**

Currently I'd need to specify two separate entities for min/max values (entity_min and entity_max). I'm trying to provide those values through homeassistant's "statistics" platform (https://www.home-assistant.io/integrations/statistics/) which provides (among others) these as well, but within the same entity, different attributes. I tried to pass the same entity both as min and max, but that doesn't seem to work.

E.g. I tried:

type: 'custom:tempometer-gauge-card'
entity: sensor.nrf24_47_pressure
min: 980
max: 1050
title: Barometer
decimals: 1
severity:
  green: 1020
  yellow: 1000
  red: 900
entity_min: sensor.nrf24_47_statistics
entity_max: sensor.nrf24_47_statistics

This just places the min/max arrows right next to each other, exactly on the current value.

**Describe the solution you'd like**

If possible, it would be nice to be able to configure the card in a way that I can pass a statistics entity to it, with optionally specifying what attributes identify the min and max values. Or is it already possible somehow just I missed/misunderstood in the documentation?

**Describe alternatives you've considered**
I could probably hand-populate different entities based on the staticstics platform sensor but that seems like an unnecessary extra step.

**Additional context**
Attached how the output looks like with the above config.
![Capture](https://user-images.githubusercontent.com/9517578/107930473-530db580-6f7b-11eb-89ed-96b734fe9753.PNG)

**Comment by bpetrikovics** [comment]
Just for clarity my statistics sensor looks like this:
   - platform: statistics
    name: nrf24_47_statistics
    entity_id: sensor.nrf24_47_pressure
    sampling_size: 720
    max_age:
      hours: 12                            

Its data currently is the following:

sampling_size: 720
count: 298
mean: 1036.94
median: 1036.8
standard_deviation: 0.45
variance: 0.21
total: 309007
min_value: 1036.1
max_value: 1037.8
min_age: 2021-02-14T21:50:29.207017+00:00
max_age: 2021-02-15T09:46:03.873220+00:00
change: -1
average_change: 0
change_rate: 0
unit_of_measurement: hPa
friendly_name: nrf24_47_statistics
icon: mdi:calculator

**Comment by SNoof85** [comment]
I'll have a look to fetch from attributes if needed for min/max
At the moment only the state of the statistic sensor is used.

**Comment by SNoof85** [comment]
Thank you for your input :)
New release 1.2 should answser what you need !

**Comment by bpetrikovics** [comment]
Awesome, thank you!
I'll upgrade and test.

**Comment by bpetrikovics** [comment]
Works perfectly! Thanks again :)
