### ISSUE TITLE
entity is undefined v1.2

### ISSUE THREAD

**Issue by valderaplets** [SNoof85/lovelace-tempometer-gauge-card#25]
**Describe the bug**
entity is undefined

**Version of the card**
-       v1.2       

entity work : 
![image](https://user-images.githubusercontent.com/63161106/107945201-940fc500-6f8f-11eb-8674-502d631126a8.png)

but with gauge-card : 

![image](https://user-images.githubusercontent.com/63161106/107945169-88240300-6f8f-11eb-84df-d83c7fb74fea.png)
![image](https://user-images.githubusercontent.com/63161106/107945004-485d1b80-6f8f-11eb-9b49-1542afe34a62.png)

**Comment by millallo** [comment]
same problem

**Comment by yfands** [comment]
me too, no matter what I put in no sensor is 'defined' according to the card..

**Comment by nibblerrick** [comment]
I have slightly different `Cannot read property 'split' of undefined` but I assume it's the same bug as it happens since 1.2, too.

**Comment by Ylinku** [comment]
The following entities are required now, not optional.
entity_min
entity_max

**Comment by nibblerrick** [comment]
Readme says min and max are required, not entity_min and entity_max. Why should entity_min and entity_max be required?

**Comment by SNoof85** [comment]
Fixed in 1.2.1
