### ISSUE TITLE
Display on mobile distorted.

### ISSUE THREAD

**Issue by TheDukeSr** [SNoof85/lovelace-tempometer-gauge-card#27]
I realy don't know if it's this card, or the Horizontal Stack card is faulty here. 
But I use that horizontal stack card on many other cards and none of them have these problems.

Version : 1.2.1

Using Home Assistant App on Samsung Galaxy S10

**Problem:**
The card bottom is cut of (check the "g" in gang).
The left and right of the card is also partly cutoff.

**Mobile screenshot.** (don't know how to get the link working when clicked here.. copy paste does work!)
[https://photos.app.goo.gl/ZDse2H2WLZM56Ccr7](https://photos.app.goo.gl/ZDse2H2WLZM56Ccr7)

On Laptop browser everything looks correct.

**Card code used:**
`type: horizontal-stack
cards:
  - type: 'custom:tempometer-gauge-card'
    entity: sensor.temperatuur_woonkamer
    style: thermometer
    min: 15
    max: 25
    entity_min: sensor.temp_woonkamer_min
    entity_max: sensor.temp_woonkamer_max
    title: Woonkamer 24hr
    severity:
      green: 20.5
      yellow: 22
      red: 22.5
  - type: 'custom:tempometer-gauge-card'
    entity: sensor.temperatuur_gang
    style: thermometer
    min: 15
    max: 25
    entity_min: sensor.temp_gang_min
    entity_max: sensor.temp_gang_max
    title: Gang 24hr
    severity:
      green: 20.5
      yellow: 22
      red: 22.5
`
I appriciate your work and realy like the card, Thnx !

**Comment by SNoof85** [comment]
Can you try to add `horizontal: true` in the cards configuration.

In general, the card doen't render well in horizontal stacks.

**Comment by TheDukeSr** [comment]
> Can you try to add `horizontal: true` in the cards configuration.

Thnx.
This fixed the right side cutoff.
Still some cutoff below, but it's not to bad.

Hope you can fix the cut below in the future to, but for now this ticked can be closed.

**Comment by SNoof85** [comment]
you can also try to remove `horizontal: true` and try `scale: 35px` but changing the scale to lower than 40px is probably not so good at render.
