### ISSUE TITLE
Custom element doesn´t exist

### ISSUE THREAD

**Issue by AlekBarta** [SNoof85/lovelace-tempometer-gauge-card#28]
Hi.
Custom card installed via HASC on HA v2021.2.1. 
Error in lovelace > scr.
![image](https://user-images.githubusercontent.com/78590355/108190059-bc273180-7111-11eb-8fbd-14248641db8d.png)

**Comment by SNoof85** [comment]
can you check if it's correctly added to your lovelace ressources ?

**Comment by AlekBarta** [comment]
Via HASC installed in /config/www/community/lovelace-tempometer-gauge-card/tempometer-gauge-card.js

**Comment by SNoof85** [comment]
Can we close this ?
