### ISSUE TITLE
Adjustable size

### ISSUE THREAD

**Issue by alidonet** [SNoof85/lovelace-tempometer-gauge-card#30]
The size is fixed, and you can't place more than two panels when horizontal stack since they're overlapping. The same problem for some screen resolutions. It will be good to use the markup, similar to the default "gauge" that resizes based on the container available space.
![Screenshot_2021-02-18 Обзор - Home Assistant](https://user-images.githubusercontent.com/7659676/108420705-35737100-7245-11eb-9eb3-532f82cc327c.png)

**Comment by SNoof85** [comment]
i have to give this a shot.

**Comment by miguelpucela** [comment]
With only two gauges, they also overlap a bit in mobile version in vertical orientation.

**Comment by miguelpucela** [comment]
Another thing is the `title`. It should be better if it is splitted multiline if it is too long.

![gauge2](https://user-images.githubusercontent.com/77801371/113269345-a55f2780-92d8-11eb-948a-e686358bb3ff.png)
