### ISSUE TITLE
More color intervals

### ISSUE THREAD

**Issue by hehrsson** [SNoof85/lovelace-tempometer-gauge-card#32]
Very nice component!

I currently use it for humidity.
It would be nice to have more flexibility for the colors.

For example if humidity goes below 20% or above 60% I want it to be red
So, not just green, yellow and red.

Example:
0-20: red
20-30: yellow
30-50: green
50-60: yellow
60-100: red

For example the mini-graph-card can be defined with unlimited thresholds, like this:
color_thresholds:
          - color: '#039BE5'
            value: 30
          - color: '#0DA035'
            value: 50
          - color: '#E0B400'
            value: 70
          - color: '#E45E65'
            value: 80

**Comment by matejzero** [comment]
I just came across the same issue and I'm looking for a "humidity card"

**Comment by mikeage** [comment]
If anyone is able to work on this, I agree that it would extremely useful for humidity, but also for temperature; too cold can be just as bad as too hot!
