### ISSUE TITLE
incorect gauge with some themes

### ISSUE THREAD

**Issue by Darkein** [SNoof85/lovelace-tempometer-gauge-card#33]
**Describe the bug**
The gauge is incorrectly hidden with default theme and some custom themes like `Noctis`. It's ok with custom theme `Slate`. The default gauge is ok with every themes

**Version of the card**
Version : 1.3

**Screenshots**
![image](https://user-images.githubusercontent.com/4948463/111496042-39a98600-8740-11eb-8f47-745441922712.png)

**Desktop :**
 - Browser : latest Chrome

**Additional context**
Installed from HACS. Thanks for your job !

**Comment by SNoof85** [comment]
The default gauge is not maid with the same code.
Mine is probably worst but this is it...
Your bug is from the css var(--card-background-color) set to be transparent.
I have no other way to do it right now i'm sorry.
I will think about a solution but don't expect it soon.

**Comment by Darkein** [comment]
Thanks for your answer, I will play with this var until then

**Comment by piasekps** [comment]
Hi @Darkein 
Did you solve your problem, already?
If so can you share your solution?

Thx

**Comment by Darkein** [comment]
I just used another theme. But It looks like the latest HA version fixed
the problem, can you try if it works for you now ?

Le lun. 5 avr. 2021 à 21:02, Sławomir Piasecki ***@***.***> a
écrit :
