### ISSUE TITLE
How about dual gauges

### ISSUE THREAD

**Issue by uSlackr** [SNoof85/lovelace-tempometer-gauge-card#34]
**Is your feature request related to a problem? **
Some appliances - think fridge- report two temps. Fridge and freezer.  It would be nice to hav03them both on the same graph

Describe the solution you'd like**

Two concentric arches would work nice

**Describe alternatives you've considered**
There is a dual graph card in HACS which I've considered.

**Comment by SNoof85** [comment]
Hello ! Thx for your input, therefore this is not something i want to work on.
If you have an alternative that's nice :)
