### ISSUE TITLE
evaluating 'entity.state'

### ISSUE THREAD

**Issue by lytryx** [SNoof85/lovelace-tempometer-gauge-card#36]
Hi, first thanks for sharing the work, it's great.

**Describe the bug**
I have installed it but it does not run correctly, does not finish loading in lovelace.

**Version of the card**
Version : 1.3

**Screenshots**
/local/community/lovelace-tempometer-gauge-card/tempometer-gauge-card.js:334:20 TypeError: undefined is not an object (evaluating 'entity.state')
/local/community/lovelace-tempometer-gauge-card/tempometer-gauge-card.js:334:21 Uncaught TypeError: Cannot read property 'state' of undefined

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 90.0.4430.85

thanks in advance

**Comment by SNoof85** [comment]
Could you show the config of the card ?

**Comment by lytryx** [comment]
yes of course ! in lovelace.yaml :


resources:
  - url: /local/community/lovelace-tempometer-gauge-card/tempometer-gauge-card.js
    type: js

     - type: 'custom:tempometer-gauge-card'
       title: Temperatura fuera
       style: thermometer
       entity: sensor.espduino_am2301_temperature
       min: 15
       max: 30
       entity_min: sensor.espduino_am2301_temperature_min_this_week
       entity_max: sensor.espduino_am2301_temperature_max_this_week
       severity:
         green: 22
         yellow: 24
         red: 27

**Comment by SNoof85** [comment]
your entity_min and entity_max are real entities with a state right ?
Try to remove them please, I suspect that you just wait for the card to compute these values but il won't be the case. You have to define your own min and max sensors.

**Comment by lytryx** [comment]
First thanks for your quick reply.
I have tried what you tell me and now it works! Yes, I thought those values ​​were calculated by the card. I will look for some sensors to obtain the min and max.
Thank you very much for sharing your work and your help
