### ISSUE TITLE
style: humidity don't show icons correctly 

### ISSUE THREAD

**Issue by elrhandouri** [SNoof85/lovelace-tempometer-gauge-card#4]
Hello again ;)
The humidity icons are all stacked at the same level, as shown below:

![Screenshot_20200105-231653_Home Assistant](https://user-images.githubusercontent.com/7691348/71786946-db4c2800-3011-11ea-8a43-75f2a0807142.jpg)

**Comment by SNoof85** [comment]
Yep, this need a fix. Tomorrow :)

Sorry

**Comment by SNoof85** [comment]
Solved ;)

Sorry about this, i need to review my code to make it more easy to change...
