### ISSUE TITLE
Resizing problem on tight cards 

### ISSUE THREAD

**Issue by enryf89** [SNoof85/lovelace-tempometer-gauge-card#41]
Hello, I have an unpleasant view of the Tempometer Gauge Card when used on narrow layouts. For example in combination with Horizontal Stack.
As you can see in the attached example from my iPhone, the card does not scale down and goes out of bound. This also happens on Desktop.

I'm not sure if this is exactly a bug or more of a feature request, but still it would be nice if it could resize as normal Gauge Cards do in HA.

Ps: loving this card.
Regards,
Enrico

![IMG_866D9CB51A12-1](https://user-images.githubusercontent.com/9007104/120304927-824cf600-c2d0-11eb-84e2-c07d0c00930a.jpeg)

**Comment by AussiSG** [comment]
Got the same problem when stacking it horizontal and viewing on my mobile phone

**Comment by AussiSG** [comment]
Problem still persists 🙂

**Comment by cratermaddie** [comment]
Also seeing this issue. The contents don't respect the card boundaries.

**Comment by cratermaddie** [comment]
This is still an issue

**Comment by AussiSG** [comment]
Still not fixed 😉

**Comment by AussiSG** [comment]
Still an issue 🙂

**Comment by bangan1910** [comment]
I'm having the problem too, which is sad. I would prefer the slimmer look compared to the normal gauge.
I guess by now that nobody have found a way to a fix, or to 'cheat' to get what we want?
