### ISSUE TITLE
visual bug when using a theme,

### ISSUE THREAD

**Issue by TimoPurzner** [SNoof85/lovelace-tempometer-gauge-card#42]
**Describe the bug**
I use the IOS-dark theme and this makes an visual bug to the component (see screenshot)

**Version of the card**
You will find this information in console of your browser.
Version : 1.31

**Screenshots**
![image](https://user-images.githubusercontent.com/9642078/120712745-53e23d00-c4c1-11eb-8437-bd19e93864e1.png)
**Desktop (please complete the following information):**
 - Opera GX (chrome)

**Comment by SNoof85** [comment]
I know this one and have no solution to offer right now...
