### ISSUE TITLE
option "show_icons" requested

### ISSUE THREAD

**Issue by Pirol62** [SNoof85/lovelace-tempometer-gauge-card#44]
I'd like to hide the icons. In a row of 6 Temperatures, the icon is very redundant.
![image](https://user-images.githubusercontent.com/48820003/129536245-9d6dec38-6813-476b-b6cd-a2b1c47a6e30.png)

Request:
Option "show_icons: true/false"
When Icon are off, the card hight should be reduced.

**Comment by SNoof85** [comment]
You can set the option `card_style` to `custom` and do not fill options icon1/2/3. No icons will be shown.
