### ISSUE TITLE
Background of Gauge not transparent

### ISSUE THREAD

**Issue by Pirol62** [SNoof85/lovelace-tempometer-gauge-card#45]
**Describe the bug**
![image](https://user-images.githubusercontent.com/48820003/129535858-a91d64f1-8b09-403c-94e2-51c416a6cc72.png)
Hi, the white background should be transparent.
How can I modify this element?

**Comment by SNoof85** [comment]
Sorry but as the card is designed you can make it transparent or you will see the gauge through it.
See #33
