### ISSUE TITLE
Overflowing when using in a grid or horizontal stack

### ISSUE THREAD

**Issue by skafsgaar** [SNoof85/lovelace-tempometer-gauge-card#48]
**Describe the bug**
The content overflows the sides when using the card in a grid or horizontal stack

**Version of the card**
Version : 1.4

**Screenshots**
<img width="418" alt="Skærmbillede 2021-11-08 kl  09 02 19" src="https://user-images.githubusercontent.com/402582/140705110-d6a65e61-01e4-46a2-bfc9-c512c5503117.png">

**Desktop (please complete the following information):**
 - Safari 15.1

**Comment by kalhimeo** [comment]
I second this, would be great to have a dynamic resize similar to the original HA gauge card. Anyway thanks a lot for your nice card !
