### ISSUE TITLE
Red color not working?

### ISSUE THREAD

**Issue by AussiSG** [SNoof85/lovelace-tempometer-gauge-card#52]
As visible in the print screen. When the value reached the point for turning the color red.
It goes to dark blue?

**Screenshots**
![image](https://user-images.githubusercontent.com/56043947/152785905-d4a4a71c-07f6-43e1-a015-723e9849b0f2.png)

**Comment by SNoof85** [comment]
The colors are taken from CSS variables. Red color is coming from  var(--label-badge-red)
So if you changed it to blue with a theme...Then you get some blue red !!!

**Comment by AussiSG** [comment]
Alright will have a look in this.

The build in gauge meter of home assistant does show the red bar...

**Comment by AussiSG** [comment]
Closed seems to be bugs in custom themes :/
