### ISSUE TITLE
high and low can both be "red"

### ISSUE THREAD

**Issue by jchhenderson** [SNoof85/lovelace-tempometer-gauge-card#54]
**Is your feature request related to a problem? Please describe.**
No related to a problem :-)

**Describe the solution you'd like**
Humidity, for example, can be uncomfortable when too high as well as too low (as can temperature).
If would be great to have severity scale that has the options of:
- "middle is best" with amber/red for both higher and lower values
- "high is best".

**Describe alternatives you've considered**
do not use colour at all.

**Additional context**
the "severity" attribute (for relative humidity) could look like:
  amber-upper: 80
  green-upper: 60
  green-lower: 40
  amber-lower: 20

which would mean:
 - below 20% is red
 - between 20% and 40% is amber
 - between 40% and 60% is green
 - between 60% and 80% is amber
 - higher than 80% is red

**Comment by jchhenderson** [comment]
...forgot to add that this is already a great card! 👍

**Comment by SNoof85** [comment]
It will be more and more complex to have everyone feature in a same card. I was asked to add an extra color already : #14 wich was introduced with : #16 
Sorry but I can't make it happen.

**Comment by jchhenderson** [comment]
> Sorry but I can't make it happen.

Thanks anyway.  I cannot find any card that is designed for the optimum reading to be in the middle (as opposed to being at the top).  Never mind.
