### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by killabeenl** [SNoof85/lovelace-tempometer-gauge-card#61]
Hello SNoof85,

I know that you stoppend working on this lovelace card. I love this card for use with my BBQ dashboard.
This is because of the Min and Max entities that can be used. I use input numbers so that the Min and Max can vary.

My question is if it is possible to change the color and size of the Min (in blue) and Max (in red)?

Would be nice if you can push me in the right direction.

Best regards,

Killabee

**Comment by SNoof85** [comment]
Hi !

I think what you are looking for is in lines from 228 to 239.

You can see the colours for recentMin and recentMax here, and also the sizes. You can adjust these settings here.

Size is on lines 229 & 235
Color is on lines 231 & 237

**Comment by killabeenl** [comment]
Thanks, I forked the code and made the changes there. Now I can change it the way I want.
